Repository nan-sso-ggong/store-management-system, pull requests merged in 2023-12, with the labels that each got.

#74 🚑 백엔드 연동시 발생한 문제점 수정
  .idea/workspace.xml
  Frontend/customer/src/Axios.js
  Frontend/customer/src/Pages/PaymentList.jsx
  Frontend/customer/src/Pages/SelectItems.jsx
  Frontend/customer/src/Pages/SelectStore.jsx
Labels: feat, fix

#76 ✨ 점주 회원가입 및 점포 추가 이미지 받도록 변경
  Frontend/Admin/package-lock.json
  cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/AuthController.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/StoreController.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Store.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/JoinRequestForManager.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/StoreRequestDto.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/AuthService.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/StoreService.kt
Labels: fix

#78 🐛 [FIX] 점주 - 점포 목록 조회 API 수정
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Store.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/StoreDetailResponseDto.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/StoreRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/StoreService.kt
Labels: fix

#82 🐛 로그아웃 후 다시 로그인 할 때 생기는 버그 수정
  .idea/workspace.xml
  Frontend/customer/src/Axios.js
  Frontend/customer/src/Pages/Login/GoogleAfterLogin.jsx
  Frontend/customer/src/Pages/Login/KakaoAfterLogin.jsx
  Frontend/customer/src/Pages/Login/NaverAfterLogin.jsx
Labels: fix

#83 [FIX] 점주 - 발주목록 조회시 카테고리 검색 양식 수정
  cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/ManagerController.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/OrderCSService.kt
Labels: fix

#84 🐛 점포 생성자 오류 수정
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Store.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/JoinRequestForManager.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/StoreService.kt
Labels: fix

#87 ✨ 잔액부족시 예외처리, 주문내역내 주문상태 색으로 구별 구현
  .idea/workspace.xml
  Frontend/customer/src/Pages/PaymentList.jsx
  Frontend/customer/src/Pages/ShoppingCart.jsx
Labels: feat

#89 ✨ 발주 목록 불러오기 구현
  cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/StoreController.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/OrderApplicationListDto.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/OrderApplicationRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/OrderApplicationService.kt
Labels: feat

#92 ✨ [FEAT] 중복 상품 예외 처리 추가
  cs25server/src/main/kotlin/edu/dongguk/cs25server/exception/ErrorCode.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/ItemHQRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ItemHQService.kt
Labels: feat

#95 [FIX] 점포 목록 조회시 전화번호 대신 주소 들어가는 버그 수정
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Store.kt
Labels: fix

#108 ✨ 점주: 주문내역 관리 모든 기능 구현
  .idea/workspace.xml
  Frontend/store/src/Pages/PaymentList.jsx
Labels: feat
