Repository nan-sso-ggong/store-management-system, pull requests merged in 2023-11, with the labels that each got.

#9 ✨ [FEAT] 본사 엔티티 추가
  cs25backend/src/main/java/edu/dongguk/cs25backend/domain/Headquarters.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/domain/ItemHQ.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/domain/OrderApplication.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/domain/type/ItemCategory.java
Labels: feat

#12 ✨ 점주 및 점포 추가
  cs25backend/.gitignore
  cs25backend/gradlew
  cs25backend/src/main/java/edu/dongguk/cs25backend/controller/AuthController.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/controller/CustomerController.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/controller/ExceptionController.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/controller/ManagerController.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/controller/StoreController.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/domain/Customer.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/domain/Headquarters.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/domain/ItemCS.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/domain/ItemHQ.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/domain/Manager.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/domain/Order.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/domain/OrderApplication.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/domain/OrderItemCS.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/domain/Store.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/domain/type/UserRole.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/dto/request/ManagerRequestDto.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/dto/request/StoreRequestDto.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/dto/response/LoginResponse.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/dto/response/RestResponse.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/exception/CS25Exception.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/exception/ErrorCode.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/repository/ManagerRepository.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/repository/StoreRepository.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/service/AuthService.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/service/ManagerService.java
  cs25backend/src/main/java/edu/dongguk/cs25backend/service/StoreService.java
  cs25backend/src/main/resources/application.yml
Labels: feat, fix

#18 ✨ [FEAT] 본사 컨트롤러 추가 및 데이터 리스트 응답 dto 추가
  cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/HeadquartersController.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Headquarters.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/ItemHQ.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/OrderApplication.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/WarehousingApplication.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/type/ItemCategory.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/type/Supplier.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/ListResponseDto.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/PageInfo.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/StockResponseDto.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/ItemHQRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ItemHQService.kt
Labels: feat

#19 ✨ 점주, 점포, 주문 엔티티 추가 및 점주 점포 추가 기능 구현
  cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/ExceptionController.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/ManagerController.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/StoreController.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/ItemCS.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Manager.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Order.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/OrderApplication.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/OrderItemCS.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Store.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/type/OrderStatus.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/ManagerRequestDto.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/StoreRequestDto.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/ManagerRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/StoreRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ManagerService.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/StoreService.kt
Labels: feat

#22 ✨ [FEAT] 본사 보유 재고 목록 조회 완료
  cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/HeadquartersController.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/ItemHQ.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/WarehousingApplication.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/type/ItemCategory.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/ItemHQRequestDto.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/StockResponseDto.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/exception/ErrorCode.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/HeadquartersRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/ItemHQRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ItemHQService.kt
Labels: feat

#24 ✨ 본사 재고 전체 목록 구현
  cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/CustomerController.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/ManagerController.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/StoreController.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/ItemCS.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Manager.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/OrderItemCS.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Store.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/ItemCSUpdateDto.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/ItemCSUpdateListDto.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/StockForStoreDto.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/StoreResponseDto.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/exception/ErrorCode.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/ItemCSRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ItemCSService.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/StoreService.kt
Labels: feat

#29 ✨ [FEAT] 본사 상품 추가 API 구현 및 이미지 업로드 기능 구현
  cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/HeadquartersController.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Image.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/ItemHQ.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/type/Extension.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/type/ImageCategory.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/exception/ErrorCode.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/ImageRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ItemHQService.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/util/FileUtil.kt
Labels: feat

#37 🐛 [FIX] 점포 관련 API Service 위치 이동 및 로직 수정
  cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/ManagerController.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Store.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/StoreRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ManagerService.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/StoreService.kt
Labels: fix

#40 ✨ [FEAT] 본사 입고 관리 발주 목록 조회 API 구현 및 enum 반환 수정
  cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/HeadquartersController.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/ItemHQ.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/OrderApplication.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/type/ItemCategory.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/type/ReleaseStatus.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/type/Supplier.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/OrderResponseDto.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/ItemHQRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/OrderApplicationRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ItemCSService.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ItemHQService.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/OrderApplicationService.kt
Labels: feat, fix

#41 ✨ 점주 및 점포 신청 승인 거절
  cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/HeadquartersController.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Manager.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/Store.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/ApplyRequestDto.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/ManagerRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/StoreRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ManagerService.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/StoreService.kt
Labels: feat

#42 ✨ 점포 신청 구현/점주, 본사 회원가입 중복 처리
  cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/ManagerController.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/StoreController.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/StoreRequestDto.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/exception/ErrorCode.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/HeadquartersRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/ManagerRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/AuthService.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/StoreService.kt
Labels: feat

#44 ✨ 장바구니 로직 구현, UI 일부 구현
  .idea/workspace.xml
  Frontend/customer/package.json
  Frontend/customer/src/Pages/SelectItems.jsx
  Frontend/customer/src/Pages/SelectStore.jsx
  Frontend/customer/src/Pages/ShoppingCart.jsx
  Frontend/customer/src/state.js
  Frontend/customer/yarn.lock
Labels: feat

#52 🚑 장바구니 api수정에 따른 변경
  .idea/workspace.xml
  Frontend/customer/src/Pages/CheckPayment.jsx
  Frontend/customer/src/Pages/ShoppingCart.jsx
Labels: feat, fix

#51 ✨ [FIX] 점주 - 주문 내역 조회 API 수정
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/CustomerOrderRequestDto.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/OrderRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/OrderRepostiory.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/OrderService.kt
Labels: fix

#56 feat: 출고 관리 API 구현
  cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/HeadquartersController.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/ItemHQ.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/OrderApplication.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/ReleaseRequestDto.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/WarehousingRequestDto.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/request/WarehousingRequestDtos.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/ReleaseStockResponseDto.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/exception/ErrorCode.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/OrderApplicationRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/StoreRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ItemHQService.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/OrderApplicationService.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/WarehousingApplicationService.kt
Labels: feat, fix

#58 ✨ [FEAT] 점주 - 발주 관리 관련 API 관련
  cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/ManagerController.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/OrderApplication.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/OrderItemResponseDto.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/dto/response/PickupOrderRequestDto.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/ItemCSRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/OrderApplicationRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/OrderCSService.kt
Labels: feat

#66 🐛 [FIX] 본사 API 버그 수정
  cs25server/src/main/kotlin/edu/dongguk/cs25server/controller/HeadquartersController.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/ItemHQ.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/OrderApplication.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/domain/WarehousingApplication.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/repository/ItemHQRepository.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/ItemHQService.kt
  cs25server/src/main/kotlin/edu/dongguk/cs25server/service/WarehousingApplicationService.kt
Labels: fix
